Attribute VB_Name = "SQL"
Function GetAllTablesString(tables As String) As String
    GetAllTablesString = "SELECT * FROM (SELECT "
    GetAllTablesString = GetAllTablesString & " T.TABLE_SCHEMA || '.' || T.TABLE_NAME AS TableName,"
    GetAllTablesString = GetAllTablesString & " T.COLUMN_NAME AS ColumnName,"
    GetAllTablesString = GetAllTablesString & " T.ORDINAL_POSITION AS OrdinalPosition,"
    GetAllTablesString = GetAllTablesString & " T.DATA_TYPE AS DataType,"
    GetAllTablesString = GetAllTablesString & " T.CHARACTER_MAXIMUM_LENGTH AS MaximumLength,"
    GetAllTablesString = GetAllTablesString & " T.CHARACTER_MAXIMUM_LENGTH AS MaximumByteLength,"
    GetAllTablesString = GetAllTablesString & " T.NUMERIC_PRECISION AS NumericPrecision,"
    GetAllTablesString = GetAllTablesString & " T.NUMERIC_SCALE AS NumericScale,"
    GetAllTablesString = GetAllTablesString & " T.ORDINAL_POSITION AS NumericPrecision表示用,"
    GetAllTablesString = GetAllTablesString & " T.IS_NULLABLE AS IsNullable,"
    GetAllTablesString = GetAllTablesString & " CASE WHEN T.IS_NULLABLE = 'YES' THEN '○' WHEN T.IS_NULLABLE = 'NO' THEN '' ELSE 'Undefined' END AS NotNull表示用,"
    GetAllTablesString = GetAllTablesString & " '' AS Default1,"
    GetAllTablesString = GetAllTablesString & " 0 AS IdentitySeed,"
    GetAllTablesString = GetAllTablesString & " 0 AS IdentityIncrement,"
    GetAllTablesString = GetAllTablesString & " '' AS Identity表示用,"
    GetAllTablesString = GetAllTablesString & " C1.constraint_type as Type,"
    GetAllTablesString = GetAllTablesString & " CASE WHEN C1.column_name is not NULL THEN '○' ELSE '' END AS PrimaryKey表示用 "
    GetAllTablesString = GetAllTablesString & "FROM"
    GetAllTablesString = GetAllTablesString & "  information_schema.columns T "
    GetAllTablesString = GetAllTablesString & "LEFT OUTER JOIN "
    GetAllTablesString = GetAllTablesString & "( "
    GetAllTablesString = GetAllTablesString & "select tc.table_schema,tc.table_name,ccu.column_name,tc.constraint_type "
    GetAllTablesString = GetAllTablesString & "from information_schema.table_constraints tc,information_schema.constraint_column_usage ccu "
    GetAllTablesString = GetAllTablesString & "where  "
    GetAllTablesString = GetAllTablesString & "tc.constraint_type='PRIMARY KEY' and tc.table_catalog=ccu.table_catalog and "
    GetAllTablesString = GetAllTablesString & "tc.table_schema=ccu.table_schema and tc.table_name=ccu.table_name and "
    GetAllTablesString = GetAllTablesString & "tc.constraint_name=ccu.constraint_name "
    GetAllTablesString = GetAllTablesString & ") C1 "
    GetAllTablesString = GetAllTablesString & "    ON  ( T.TABLE_SCHEMA=C1.table_schema AND T.TABLE_NAME = C1.TABLE_NAME AND T.COLUMN_NAME=C1.COLUMN_NAME) "
    GetAllTablesString = GetAllTablesString & "WHERE"
    GetAllTablesString = GetAllTablesString & "  T.table_schema != 'pg_catalog' and T.table_schema != 'information_schema' "
    GetAllTablesString = GetAllTablesString & "Order By T.TABLE_SCHEMA,T.TABLE_NAME,T.ORDINAL_POSITION) AS TOTALSUM"
    If tables <> "" Then GetAllTablesString = GetAllTablesString & " WHERE TableName ~ '" & tables & "'"
End Function

